# Configuration file for DroneSoundSeparator

# Data configuration
# configs/config.yaml
data:
  mixtures_dir: data/mixtures
  clean_dir: data/clean_drone_16ch
  noise_dir: data/noise_16ch
  dataset_overview: data/mixtures/dataset_overview.json
  sample_rate: 44100           # Target sample rate
  max_audio_length: 3.0
  train_test_split: 0.8        # Proportion of data used for training
  snr_levels: [-5, 0, 5, 10]   # SNRs used for mixing

# Audio processing parameters
n_fft: 2048
hop_length: 441
win_length: 2048
max_audio_length: 3.0        # Maximum segment length (longer inputs will be split)

# Model parameters
model:
  in_channels: 16 
  base_channels: 32
  dropout_rate: 0.2
  use_batch_norm: true
  n_fft: 2048
  hop_length: 441 
  win_length: 2048

# Training parameters
training:
  use_amp: true              # Enable automatic mixed precision
  gradient_accumulation_steps: 4  # Accumulate gradients over 4 batches
  max_gpu_mem: 0.85         # Target GPU memory utilization
  batch_size: 16
  epochs: 50
  lr: 0.0003
  lr_scheduler:
    use: true
    type: "cosine"           # "step", "cosine", "plateau"
    step_size: 10
    gamma: 0.5
    patience: 5              # For plateau scheduler
    min_lr: 1e-7             # Prevent LR from decaying below this
  optimizer: "adam"          # "adam", "adamw", "sgd"
  weight_decay: 0.0001
  early_stopping:
    patience: 10
    min_delta: 0.001

# Validation parameters
validation:
  use_amp: true              # Enable automatic mixed precision
  interval: 1                 # Validate every N epochs
  batch_size: 32
  save_samples_interval: 5    # Save samples every 5 epochs

# Evaluation parameters
evaluation:
  use_amp: true
  max_retries: 3
  batch_reduction_factor: 2
  default_batch_size: 8

# Checkpoint parameters
checkpoints:
  save_rng_state: true       # Save random states
  save_optimizer_state: true
  save_dir: experiments/run1
  save_best_only: true       # Only save when validation metric improves
  save_frequency: 5          # Save every N epochs (if save_best_only=false)

# Hardware settings
device: cuda                  # "cuda" or "cpu"
num_workers: 4                # Number of workers for data loading
pin_memory: true             # crucial for asynch transfers

# Data loader optimizations
prefetch_factor: 2  # Preload next batches
persistent_workers: true  # Maintain worker pool

# Logging parameters
logging:
  use_tensorboard: true
  log_dir: experiments/run1/logs
  image_freq: 100            # Log spectrograms every N steps
